//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_force : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean toggleForce
        {
            get
            {
                return SteamVR_Actions.force_toggleForce;
            }
        }
        
        public virtual SteamVR_Action_Boolean pushForce
        {
            get
            {
                return SteamVR_Actions.force_pushForce;
            }
        }
        
        public virtual SteamVR_Action_Boolean pullForce
        {
            get
            {
                return SteamVR_Actions.force_pullForce;
            }
        }
    }
}
